# Generated by Django 5.2.1 on 2025-05-13 08:27

import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='شماره کارت')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('iban_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبا')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شعبه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='BankAccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('old_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت قدیمی')),
                ('old_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب قدیمی')),
                ('old_iban_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبای قدیمی')),
                ('old_bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بانک قدیمی')),
                ('old_bank_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شعبه قدیمی')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.bankaccount', verbose_name='حساب بانکی')),
            ],
            options={
                'verbose_name': 'تاریخچه حساب بانکی',
                'verbose_name_plural': 'تاریخچه\u200cهای حساب بانکی',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, help_text='شماره شناسایی منحصر به فرد کارمند در سازمان.', max_length=50, null=True, unique=True, verbose_name='شماره پرسنلی')),
                ('national_code', models.CharField(blank=True, help_text='کد ملی ۱۰ رقمی و منحصر به فرد.', max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employees.models.employee_image_upload_path, verbose_name='تصویر پرسنلی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متاهل')], default='single', max_length=20, verbose_name='وضعیت تأهل')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='تعداد فرزندان')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارکنان',
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='employees.employee', verbose_name='کارمند'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سازمان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_organizations', to='employees.organization', verbose_name='سازمان والد')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_memberships', to='employees.employee', verbose_name='کارمند')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='employees.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'عضویت سازمانی',
                'verbose_name_plural': 'عضویت\u200cهای سازمانی',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='organizations',
            field=models.ManyToManyField(related_name='employees', through='employees.EmployeeOrganization', to='employees.organization', verbose_name='سازمان\u200cها'),
        ),
    ]
