# Generated by Django 5.2.1 on 2025-05-13 11:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccounthistory',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='employeeorganization',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeorganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'کارمند', 'verbose_name_plural': 'کارکنان'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='iban_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='number_of_children',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 11, 23, 5, 982526, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 11, 23, 31, 747017, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='fire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 11, 23, 35, 30554, tzinfo=datetime.timezone.utc), verbose_name='تاریخ استخدام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personnel_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد پرسنلی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_code',
            field=models.CharField(default=datetime.datetime(2025, 5, 13, 11, 23, 42, 902553, tzinfo=datetime.timezone.utc), max_length=10, unique=True, verbose_name='کد ملی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('employee', 'bank_name', 'account_number'), name='unique_bank_account_per_employee_bank'),
        ),
        migrations.DeleteModel(
            name='BankAccountHistory',
        ),
        migrations.DeleteModel(
            name='EmployeeOrganization',
        ),
    ]
