# Generated by Django 5.2.1 on 2025-05-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_bankaccounthistory_bank_account_and_more'),
        ('settings_app', '0002_alter_fiscalyear_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
