# Generated by Django 5.2.1 on 2025-05-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_remove_bankaccounthistory_bank_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام سازمان')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد سازمان')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع عضویت')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان عضویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='عضویت فعال')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_organizations', to='employees.employee', verbose_name='کارمند')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_organizations', to='organizations.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'عضویت کارمند در سازمان',
                'verbose_name_plural': 'عضویت\u200cهای کارمندان در سازمان\u200cها',
                'ordering': ['organization', 'employee', 'start_date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'organization', 'start_date'), name='unique_employee_organization_start')],
            },
        ),
    ]
