# Generated by Django 5.2.1 on 2025-05-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سال مالی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='employees.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'سال مالی',
                'verbose_name_plural': 'سال\u200cهای مالی',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره مالی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_periods', to='settings_app.fiscalyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'دوره مالی',
                'verbose_name_plural': 'دوره\u200cهای مالی',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ سقف بیمه')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_ceilings', to='settings_app.fiscalyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'سقف بیمه',
                'verbose_name_plural': 'سقف\u200cهای بیمه',
            },
        ),
        migrations.CreateModel(
            name='TaxLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_title', models.CharField(max_length=100, verbose_name='عنوان سطح مالیاتی')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='از مبلغ')),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='تا مبلغ')),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد مالیات')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_levels', to='settings_app.fiscalyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'سطح مالیاتی',
                'verbose_name_plural': 'سطوح مالیاتی',
                'ordering': ['from_amount'],
            },
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_fiscal_year_title_per_org'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='fiscal_year_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'name'), name='unique_financial_period_name_per_year'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='financial_period_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='insuranceceiling',
            constraint=models.UniqueConstraint(fields=('fiscal_year',), name='unique_insurance_ceiling_per_year'),
        ),
        migrations.AddConstraint(
            model_name='taxlevel',
            constraint=models.CheckConstraint(condition=models.Q(('from_amount__lt', models.F('to_amount'))), name='tax_level_from_before_to'),
        ),
    ]
