# Generated by Django 5.2.1 on 2025-05-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='organizations.organization', verbose_name='سازمان'),
        ),
    ]
